FROM openjdk:11 AS BUILD-IMAGE
RUN apt update && apt install maven -y
RUN git clone https://github.com/saturoldan/vprofile-project.git
RUN cd vprofile-project && git checkout docker && mvn install

FROM tomcat:9-jre11
RUN rm -fr /usr/local/tomcat/webapps/*
COPY --from=BUILD-IMAGE vprofile-project/target/vprofile-v2.war /usr/local/tomcat/webapps/ROOT.war
EXPOSE 8080
CMD [ "catalina.sh","run" ]